# Generated by Django 3.2 on 2021-04-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='category',
            field=models.CharField(choices=[('Seminar', 'Seminar')], default='null', max_length=100),
        ),
    ]
