# Generated by Django 3.2 on 2021-04-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='day_rem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='category',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Placement', 'Placement')], default='null', max_length=100),
        ),
    ]
