# Generated by Django 3.2 on 2021-04-28 13:39

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210428_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=event.models.upload_location),
        ),
    ]
