# Generated by Django 3.2 on 2021-04-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventpost_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUpdates',
        ),
    ]
